services:
  db:
    image: postgres:15
    container_name: expense-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    image: aman99jnvchd/expense-tracker-backend
    container_name: expense-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/expense_db
    volumes:
      - ./backend:/app
  
  frontend:
    build:
      context: ./frontend
    image: aman99jnvchd/expense-tracker-frontend
    container_name: expense-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
